### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by whysoserious** [ethereumproject/parity#2]
Quick install procedure fails on Ubuntu 16.04.1 LTS:
```bash
$ cargo install --git https://github.com/ethcore/parity.git parity
    Updating git repository `https://github.com/ethcore/parity.git`
failed to parse manifest at `/home/jan/.cargo/git/checkouts/parity-dd7fc9e0b8e32399/master/Cargo.toml`

Caused by:
  could not parse input as TOML
.cargo/git/checkouts/parity-dd7fc9e0b8e32399/master/Cargo.toml:63:9 expected a key but found an empty string
.cargo/git/checkouts/parity-dd7fc9e0b8e32399/master/Cargo.toml:63:9-63:10 expected `.`, but found `'`
```

Building from source fails as well:
```bash
$ git clone https://github.com/ethcore/parity
Cloning into 'parity'...
remote: Counting objects: 95456, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 95456 (delta 59), reused 3 (delta 3), pack-reused 95290
Receiving objects: 100% (95456/95456), 83.09 MiB | 26.22 MiB/s, done.
Resolving deltas: 100% (68852/68852), done.
Checking connectivity... done.
$ cd parity/
$ cargo build --release
failed to parse manifest at `/home/jan/Dev/parity/Cargo.toml`

Caused by:
  could not parse input as TOML
Cargo.toml:63:9 expected a key but found an empty string
```

Simple one-line installer for Mac and Ubuntu works as expected.

**Comment by splix** [comment]
They just renamed to `paritytech`. I'll merge upstream to update docs.

btw, I suggest to build from upstream directly, we use that fork just to make pull requests

**Comment by ghost** [comment]
What version do you want to install, stable v1.5, beta v.1.6 or definitly nightly from master?

**Comment by ghost** [comment]
master branch (by default), it's not stable dev version, it's normal that it doesn't work ;)

**Comment by ghost** [comment]
For me it works, please send to us `cargo --version` and `rustc --version --verbose`.

**Comment by whysoserious** [comment]
```bash
$ cargo --version
cargo 0.8.0 (built 2016-03-22)
$ rustc --version --verbose
rustc 1.7.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.7.0
```

**Comment by whysoserious** [comment]
> What version do you want to install, stable v1.5, beta v.1.6 or definitly nightly from master?

I wanted to successfully go through `Quick install procedure` :)

**Comment by whysoserious** [comment]
> btw, I suggest to build from upstream directly, we use that fork just to make pull requests

It would be a good idea to put that information in `README.md`

**Comment by ghost** [comment]
Good, just download deb package from https://github.com/paritytech/parity/releases/tag/v1.5.11

**Comment by ghost** [comment]
And look at that issue - https://github.com/rust-lang/cargo/issues/3378

**Comment by whysoserious** [comment]
:+1:
